import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from '@mui/material/CssBaseline';
import theme from "@/theme";
import NavBar from "@/components/Navbar";
import { ModalProvider } from "@/components/modals/ModalProvider";

// import localFont from 'next/font/local'

// example/sandbox: local font. do not delete
// const myFont = localFont({
//   src: './my-font.woff2',
// })

// variable fonts: one file for all sizes/variations eg italics
// next self hosts fonts to optimally load web fonts with no layout shift
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  breadcrumbs
}: Readonly<{
  breadcrumbs: React.ReactNode,
  children: React.ReactNode;
}>) {
  // breadcrumbs uses parallel routes (using @ dir naming) and slot components to use dynamic url ids as params are not available in root layout.tsx as does not have dynamic url at that point
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.className}`}>
        <AppRouterCacheProvider options={{ key: 'mui' }}>
          <ThemeProvider theme={theme}>
            {/* ensure consistency across browsers */}
            <CssBaseline />
            <ModalProvider>
            <NavBar />
            {breadcrumbs}
            {children}
            </ModalProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
